GET http://localhost:3003/api/users/

###
GET http://localhost:3003/api/users/243525

###
POST http://localhost:3003/api/users/ HTTP/1.1
content-type: application/json

{
    "notes": [],
    "username": "olli",
    "name": "Olli Tee",
    "password": "passsee"
}